---
title: "API Lab"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dataRetrieval)
library(ggplot2)
library(metajam)
library(tidyverse)
library(here)
```

USGS API


```{r}
siteNumber <- "11118500" 
ChoptankInfo <- readNWISsite(siteNumber)
parameterCd <- "00060"

#Raw daily data:
rawDailyData <- readNWISdv(siteNumber,parameterCd,
                      "2019-10-01","2020-10-05")
```



```{r}
ggplot(data = rawDailyData, aes(x = Date, y = X_00060_00003)) +
  geom_point() +
  labs(title = "Discharge time-series for the Ventura River from 2019-10-01 to 2020-10-05",
       y = "Discharge (cubic feet per second)",
       x = "Time")
                      
```




```{r}
# data_obj <- "https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9e123f84-ce0d-4094-b898-c9e73680eafa"
# path <- "~/Documents/MEDS/EDS213/Week2/EDS213_API_Lab"
# download_d1_data(data_obj, path)
# my_data <- read_d1_files("~/Documents/MEDS/EDS213/Week2/EDS213_API_Lab/doi_10.18739_A2RV0D11H__Alaska_Schools_Rentention2009_15__csv")
my_data_frame <- read.csv("~/Documents/MEDS/EDS213/Week2/EDS213_API_Lab/doi_10.18739_A2RV0D11H__Alaska_Schools_Rentention2009_15__csv/Alaska_Schools_Rentention2009_15.csv")

```


Household Language


```{r}
# Household language 

household_language <- read.csv(here("household_language.csv"))

household_language1 <- household_language %>% 
  select(Year, speak_only_english, total) %>% 
  filter(Year >= 2009) %>% 
  group_by(Year) %>% 
  summarise(total_eng = sum(speak_only_english), total = sum(total)) %>% 
  mutate(percent = total_eng / total)


household_language1_plot = ggplot(household_language1, aes(x = Year, y = percent)) +
  geom_point() +
  labs(title = "Percent of Alaskan Households that only Speak English",
       y = "Percent",
       x = "Year")
    

household_language1_plot
```




```{r}
# Santa Paula Creek

siteNumber <- "11113500" 
ChoptankInfo <- readNWISsite(siteNumber)
parameterCd <- "00060"

#Raw daily data:


october_4_rainfall_test_sp <- readNWISdata(sites="11113500", service="iv", 
                   parameterCd="00060", 
                   startDate="2020-10-04T00:00",endDate="2020-10-05T12:00",
                   tz="America/Chicago")
```


```{r}
october_4_rainfall_plot_sp <- ggplot(data = october_4_rainfall_test_sp, aes(x = dateTime, y = X_00060_00000)) +
  geom_line() + 
  labs(title = "Santa Paula Stream Flow Response to October 4TH, 2021 Rain Event ", 
       y = "Discharge (cubic feet per second",
       x = "Time")


october_4_rainfall_plot_sp
```

```{r}
# Ventura

siteNumber <- "11118500" 
ChoptankInfo <- readNWISsite(siteNumber)
parameterCd <- "00060"

#Raw daily data:


october_4_rainfall_test_v <- readNWISdata(sites="11118500", service="iv", 
                   parameterCd="00060", 
                   startDate="2020-10-04T00:00",endDate="2020-10-05T12:00",
                   tz="America/Chicago")
```

```{r}
october_4_rainfall_plot_v <- ggplot(data = october_4_rainfall_test_v, aes(x = dateTime, y = X_00060_00000)) +
  geom_line() +
   labs(title = "Ventura Stream Flow Response to October 4TH, 2021 Rain Event ", 
       y = "Discharge (cubic feet per second",
       x = "Time")


october_4_rainfall_plot_v
```


I used rbind() to combine the two sites. Another way to pull data from multiple locations could be to 
add multiple siteNumbers. 


```{r}
rainfall_combined <- rbind(october_4_rainfall_test_v, october_4_rainfall_test_sp)


ggplot(data = rainfall_combined, aes(x = dateTime, y = X_00060_00000, 
                                     color = site_no)) +
  geom_line() +
  labs(title = "Ventura and Santa Paula Stream Flow Response to October 4th, 2021 Rain Event",
       x = "Time",
       y = "Discharge (cubic feet per second")
```


Stream Flow peaked at both locations around 12:00 PM on October 5th.
